name: Build and Run Backend Test Coverage

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Run Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version}}

      - name: Clean install dependencies
        run: npm ci
        working-directory: ./backend

      - name: Test coverage
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          test-script: npm run test:cov
