name: Build and Test Backend Application

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      # Change to backend directory
      - name: Change to Backend Directory
        run: cd backend

      - name: Build with Maven
        run: mvn clean verify
        working-directory: ./backend # Specify the working directory for Maven

      - name: Test Report
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: SpringBoot Report # Name of the folder
          path: backend/target/site/serenity/ # Adjust path to test results relative to backend directory
