name: Build and Test Client Application
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Change to Client directory
        run: cd client

      - name: Install modules
        run: npm i
        working-directory: ./client

      - name: Run tests
        run: npm run test
        working-directory: ./client
